-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, p.PRICE * SUM(o.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE o LEFT JOIN PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;
