-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h INNER JOIN CAR_RENTAL_COMPANY_CAR c 
ON h.CAR_ID = c.CAR_ID
WHERE h.START_DATE LIKE '%-10-%' AND c.CAR_TYPE = '세단'
ORDER BY c.CAR_ID DESC;
